platform:
  - x64
  - x86

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

build: off

init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade pip
  - python -m pip install conan numpy

install:
  - conan remote add libtorrent https://api.bintray.com/conan/rllola80/Libtorrent
  - conan install --build=missing .
  - conan build .
  - mv libtorrent.pyd lib/libtorrent.pyd

test_script:
  - python test.py

after_test:
  - 7z a build-windows-%PLATFORM%.zip lib/__init__.py lib/libtorrent.lib lib/libtorrent.pyd src/* __init__.py TorrentPlugin.py AlertEncoder.py test.py
  - dir

deploy:
  provider: GitHub
  auth_token:
    secure: 6eX2olaIxe4TsfETod+SYOyDsIKwmDivjirb7RPvl/Zd4zYW3dzGr4MieJ2BP89P # your encrypted token from GitHub
  artifact: build-windows-$(PLATFORM).zip
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
