image: Visual Studio 2019

platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python38-x64"
      PYV: "3.8"
    - PYTHON: "C:\\Python37-x64"
      PYV: "3.7"
artifacts:
  - path: build-windows-*.zip

build: off

init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade pip
  - python -m pip install numpy

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - nmake libtorrent-repo
  - dir
  - curl -LO https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/boost_1_74_0.zip
  - unzip -q boost_1_74_0.zip
  - cmd: set BOOST_ROOT=C:/projects/zeronet-torrent-plugin/boost_1_74_0
  - cmd: set BOOST_BUILD_PATH=C:/projects/zeronet-torrent-plugin/boost_1_74_0/tools/build
  - cd C:/projects/zeronet-torrent-plugin/boost_1_74_0/ 
  - bootstrap.bat
  - cmd: echo using msvc ; >>%HOMEDRIVE%%HOMEPATH%/user-config.jam
  - cd C:\projects\zeronet-torrent-plugin\libtorrent-repo\bindings\python
  - C:/projects/zeronet-torrent-plugin/boost_1_74_0/b2 release --debug-configuration address-model=64 cxxstd=14 python=%PYV% libtorrent-link=static boost-link=static
  - cp C:\projects\zeronet-torrent-plugin\libtorrent-repo\bindings\python\bin\msvc-14.2\release\address-model-64\cxxstd-14-iso\python-%PYV%\threading-multi\libtorrent.pyd C:\projects\zeronet-torrent-plugin\libtorrent
  - cp C:\projects\zeronet-torrent-plugin\libtorrent-repo\bindings\python\bin\msvc-14.2\release\address-model-64\cxxstd-14-iso\python-%PYV%\threading-multi\libtorrent.lib C:\projects\zeronet-torrent-plugin\libtorrent
  - cd C:\projects\zeronet-torrent-plugin

test_script:
  - python test.py

after_test:
  - 7z a build-windows-%PYV%.zip libtorrent/__init__.py libtorrent/libtorrent.lib libtorrent/libtorrent.pyd __init__.py TorrentPlugin.py AlertEncoder.py test.py plugin_info.json

deploy:
  provider: GitHub
  auth_token:
    secure: dSaK+GaXURrAcZoxypp7VRGj7JLzSdBvQLkOZh5tAAn4wyyCMzaH4DqXgrLtAy1h
  artifact: build-windows-*.zip
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
