image: Visual Studio 2019

platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

artifacts:
  - path: build-windows.zip

build: off

init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade pip
  - python -m pip install numpy

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - nmake libtorrent
  - curl -LO https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/boost_1_74_0.zip
  - dir
  - unzip boost_1_74_0.zip
  - set BOOST_ROOT=%HOME%\zeronet-torrent-plugin \boost_1_74_0
  - set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
  - cd %BOOST_ROOT% && .\bootstrap.bat
  - echo using msvc ; >>%HOMEDRIVE%%HOMEPATH%\user-config.jam
  - cd libtorrent/bindings/python && %BOOST_ROOT%/b2 release --debug-configuration cxxstd=17 python=3.7 libtorrent-link=static boost-link=static

test_script:
  - python test.py

after_test:
  - 7z a build-windows.zip lib/__init__.py lib/libtorrent.lib lib/libtorrent.pyd __init__.py TorrentPlugin.py AlertEncoder.py test.py
  - dir

deploy:
  provider: GitHub
  auth_token:
    secure: 6eX2olaIxe4TsfETod+SYOyDsIKwmDivjirb7RPvl/Zd4zYW3dzGr4MieJ2BP89P # your encrypted token from GitHub
  artifact: build-windows.zip
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
